
<p><strong>&nbsp;I.&nbsp;&nbsp;&nbsp;&nbsp; Általános rendelkezések</strong></p>
<p>&nbsp;1.&nbsp;&nbsp;&nbsp; Az jelen Általános Szerződési Feltételek (a továbbiakban: ÁSZF) határozzák meg a www.mindmegette.hu internetes honlap (a továbbiakban: Honlap) tartalomszolgáltatójának a Mediaworks Magazines Kiadó Kft. (székhely: 1082 Budapest, Futó u. 35-37., cégjegyzékszám: 01-09-185327, adószáma: 24841973-2-43; továbbiakban Szolgáltató) és Honlapot használó természetes személyek (a továbbiakban: Felhasználó) között a Honlap felhasználása során keletkező jogokat és kötelezettségeket.</p>
<p>&nbsp;2.&nbsp;&nbsp;&nbsp; A Honlap látogatásával és használatával Ön Felhasználónak minősül és elfogadja az alábbi felhasználási feltételeket és adatvédelmi szabályzatot.</p>
<p>&nbsp;3.&nbsp;&nbsp;&nbsp; A Szolgáltató tájékoztatja Önt, mint Felhasználót, és Felhasználó kifejezetten tudomásul veszi, hogy a Szolgáltató jogosult az ÁSZF-et egyoldalúan módosítani a Szolgáltató által nyújtott szolgáltatások színvonalának növelése, hatékonyabbá tétele, valamint új szolgáltatás bevezetése érdekében.</p>
<p>&nbsp;<strong>II.&nbsp; Felhasználási Feltételek</strong></p>
<p>&nbsp;1.&nbsp;&nbsp;&nbsp; &nbsp;A Honlap felhasználása a Felhasználó által az alábbi módokon történhet:</p>
<p>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a Honlap látogatása: ingyenes és személyes adatok megadása nem szükséges,</p>
<p>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a Honlap használata (tartalom feltöltése és hozzászólás) regisztrációhoz kötött, melynek során Ön köteles megadni a következő személyes adatokat (név, lakcím, születési hely és idő, e-mail cím, felhasználói név, jelszó).</p>
<p>&nbsp;2.&nbsp;&nbsp;&nbsp; Ön beleegyezik abba, hogy a Honlapot kizárólag a saját kockázatára használja, és elfogadja, hogy az Üzemeltető nem vállal felelősséget a használat során esetlegesen felmerülő vagyoni vagy nem vagyoni károkért. A Felhasználó köteles minden tőle elvárhatót megtenni személyes adatainak, különösen az Üzemeltető által nyújtott szolgáltatások igénybevételéhez szükséges jelszó védelmének az érdekében. A Felhasználó felelősséggel tartozik minden olyan eseményért, tevékenységért, mely bejelentkezési azonosítójának, illetve jelszavának felhasználásával valósult meg.</p>
<p>&nbsp;3.&nbsp;&nbsp;&nbsp; A Szolgáltató haladéktalanul értesítést küld a Felhasználónak a felhasználói azonosítóval történő minden jogosulatlan használatról, egyéb visszaélésről.</p>
<p>&nbsp;4.&nbsp;&nbsp;&nbsp; A Szolgáltató fenntartja magának a jogot, hogy minden további értesítés nélkül törölje azon felhasználókat, akik bármely más személy nevével, képmásával, e-mail címével vagy más személyes információjával visszaélnek.</p>
<p>&nbsp;5.&nbsp;&nbsp;&nbsp; A Felhasználó a regisztrációval kötelezettséget vállal arra, hogy az általa szabadon szerkeszthető levéltartalom valamint a profiljában feltüntetésre kerülő vagy általa közzétett adatok, információk, fotók a Szolgáltató vagy harmadik személy jogát vagy jogos érdekét nem sérti. Amint a Szolgáltató tényleges tudomást szerez a vélelmezett félrevezető azonosító használatáról vagy egyéb visszaélésről, a Szolgáltató jogosult a Felhasználó hozzáférését az ellenőrzési folyamat lezárásáig korlátozni.</p>
<p>&nbsp;6.&nbsp;&nbsp;&nbsp; A Szolgáltató a Honlapon történő regisztrációkor megadott jelszó elfelejtése esetén kizárólag az "elfelejtett jelszó" funkcióval ad lehetőséget annak pótlására. Az elfelejtett jelszó pótlásához szükséges a regisztrációnál megadott e-mail cím ismerete. Az elfelejtett jelszó funkció új jelszó megadására ad lehetőséget, a régi jelszót a Szolgáltató semmilyen formában nem teszi hozzáférhetővé, még az eredeti tulajdonosának sem.</p>
<p>&nbsp;7.&nbsp;&nbsp;&nbsp; A Felhasználó a felhasználói személyes adatokban bekövetkezett változásokat a felhasználói profil oldalon állíthatja be vagy módosíthatja.</p>
<p>&nbsp;8.&nbsp;&nbsp;&nbsp; A Honlap hírlevelei az azokban található leiratkozás linken keresztül mondhatók le.</p>
<p>&nbsp;9.&nbsp;&nbsp;&nbsp; Az Üzemeltető és annak társvállalatai, partnerei, beszállítói, tanácsadói és ügynökei kizárnak minden felelősséget az elhelyezett információk vagy anyagok hitelességéért, tartalmáért, teljességéért, jogszerűségéért, megbízhatóságáért, működőképességéért vagy rendelkezésre állásáért. Az Üzemeltető kizár bármely és minden felelősségét a Felhasználók által tanúsított magatartásért.</p>
<p>&nbsp;10. A Szolgáltató fenntartja magának a jogot, hogy a szolgáltatását bármely felhasználó felé megtagadja.</p>
<p>&nbsp;11. Ön teljes mértékben felelős azért a tartalomért, amit a Honlapon elhelyez, ideértve elsődlegesen, de nem kizárólagosan a fényképeket, személyes adatokat, beszélgetéseket, listákat, osztályozásokat, személyes üzeneteket - és bármely tartalom következményeit is.</p>
<p>&nbsp;12. A Felhasználó nem módosíthatja a rendszer megjelenését, működését, illetve tilos bármilyen módon beavatkoznia, vagy megzavarnia a Honlap, a szerverek, a Honlaphoz kapcsolódó hálózat működését, továbbá tilos figyelmen kívül hagynia a Honlaphoz kapcsolódó hálózat működésére vonatkozó bármely előírás vagy szabályzat által lefektetett követelményeket, eljárási előírásokat. Az erre vonatkozó kísérletek kizárást és egyéb jogi következményeket vonhatnak maguk után.</p>
<p>&nbsp;13. A Szolgáltató kizárja felelősségét a tartalommal való bármely igényérvényesítés esetén, a tartalmat feltöltő Felhasználó a feltöltéssel korlátlan szavatosságot és helytállási kötelezettséget vállal bármely jogszabálysértés vagy egyéb igényérvényesítés miatt eljáró szervektől vagy harmadik személyektől érkező igények esetére, egyben a tartalom feltöltése előtt köteles gondoskodni a tartalom közzétételéhez szükséges minden engedély és jogosultság megszerzéséről.</p>
<p>&nbsp;14. A Szolgáltató a Honlapon közzétett információkat, adatokat, tartalmakat jogosult, de nem köteles ellenőrizni.</p>
<p>&nbsp;15. A Szolgáltató, mint közvetítő szolgáltató nem felelős a továbbított információért. Ön megértette és hozzájárul ahhoz, hogy a Szolgáltató minden értesítés nélkül eltávolítsa az olyan anyagokat, amelyeket a kizárólagos döntési jogkörében jogellenesnek, más személyiségi jogába ütköző, tisztességtelennek, fenyegetőnek, becsületsértőnek, rágalmazónak, obszcénnek vagy egyébként kifogásolhatónak talál.</p>
<p><strong>&nbsp;III.&nbsp;&nbsp; A Honlap tartalmára vonatkozó szerzői jogok, magáncélú felhasználás, átvétel</strong></p>
<p>&nbsp;1.&nbsp;&nbsp;&nbsp; A Honlapon közzétett minden tartalom szerzői jogi védelem alatt áll, amely a Szolgáltató szellemi alkotását képezi a szerzői jogról szóló 1999. évi LXXVI. törvény szerint.</p>
<p>&nbsp;2.&nbsp;&nbsp;&nbsp; A Felhasználó a Honlap tartalmáról, annak egyes részeiről kizárólag magán célból készíthet másolatot, nyomtathatja ki azt. A Honlap tartalmának magán célból, akár digitális, akár fizikai adathordozón rögzített másolatának további felhasználására (különösen, de nem kizárólag többszörözni, terjeszteni, adatbázisban tárolni, letölthetővé tenni, kereskedelmi forgalomba hozni, átdolgozni) nem jogosult. A magáncélú felhasználás jövedelemszerzést vagy jövedelemfokozás célját közvetve sem szolgálhatja.</p>
<p>&nbsp;3.&nbsp;&nbsp;&nbsp; Amennyiben Ön a saját weboldalára, közösségi oldalára (a Recepteket kivéve) tartalmat kíván átvenni a Honlapról, azt kizárólag oly módon teheti meg, hogy a cikkcímét és tartalmának rövid összefoglalóját (Leadet) a képi elemek nélkül, változatlan tartalommal és hiánytalanul átveszi a Honlapról, és a forrást megjelölve a cikk teljes tartalmára mutató hiperhivatkozást (közvetlen linket) helyez el a címben vagy a lead alá.</p>
<p>&nbsp;4.&nbsp;&nbsp;&nbsp; Amennyiben Ön a saját weboldalára, közösségi oldalára Receptet kíván átvenni a Honlapról, azt kizárólag oly módon teheti meg, hogy a Szolgáltató előzetes írásbeli engedélyét követően a Recept pontos nevét feltünteti, képi elem nélkül és a receptre mutató hiperhivatkozást helyez el a címben vagy a leadként az alá.</p>
<p>&nbsp;5.&nbsp;&nbsp;&nbsp; A fent meghatározott átvétel semmilyen esetben sem történhet üzletszerűen.</p>
<p>6.&nbsp;&nbsp;&nbsp; A fent meghatározott felhasználási jogok kiterjednek a Honlapon található szerzői jogi, szabadalmi, védjegy vagy egyéb törvényi oltalomban részesülő tartalomra is, amelynek jogosultja a Szolgáltató.</p>
<p>&nbsp;7.&nbsp;&nbsp;&nbsp; A fentiektől eltérő módon vagy mértékben történő átvétel szerzői jogot sért, és minden esetben jogi következményeket von maga után, továbbá minden egyéb a törvényi korlátozást átlépő felhasználás csak a Szolgáltató előzetes, írásbeli engedélyével lehetséges.</p>
<p>&nbsp;8.&nbsp;&nbsp;&nbsp; Ön tudomásul veszi és hozzájárul, hogy az Ön által a Honlapra feltöltött szöveges és képi tartalomra (pl: receptleírás, arckép, ételfotó) a feltöltéssel egyidejűleg, kizárólagos, határozatlan időre szóló, területi korlátozástól mentes, ellenszolgáltatás nélküli, harmadik személyekre átruházható felhasználási jogot enged a Szolgáltató részére. A Szolgáltató a feltöltött tartalmakat a felhasználási joga keretében jogosult területi és időbeli korlátozás nélkül, részben vagy egészben felhasználni, többszörözni, átdolgozni vagy átruházni, vagy bármely egyéb ismert felhasználási módon használni. A Szolgáltató elsődlegesen a magyarországi Mediaworks Hungary cégcsoport érdekeltségi körébe tartozó print és online kiadványokban használja fel a tartalmakat. Ön a felhasználási díjról a tartalom feltöltésével egyidejűleg a jelen ÁSZF elfogadásával kifejezetten lemond.</p>
<p>&nbsp;9.&nbsp;&nbsp;&nbsp; Ön megértette és hozzájárul ahhoz, hogy a Szolgáltató minden értesítés nélkül eltávolítsa az olyan anyagokat, melyek megsértik vagy megszegik bármely fél szellemi alkotáshoz fűződő jogát, szerzői és szomszédos vagy egyéb tulajdonosi jogát vagy a jelen felhasználási feltételekben foglalt rendelkezéseket. Ezekben az esetekben a Szolgáltató minden értesítés nélkül törölheti a felhasználót.</p>
<p><strong>&nbsp;IV.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Adatkezelési nyilatkozat</strong></p>
<p>&nbsp;Fogalmak</p>
<p>&nbsp;Személyes adat<br>A Felhasználóval kapcsolatba hozható adat - különösen a felhasználó neve, azonosító jele, valamint egy vagy több fizikai, fiziológiai, mentális, gazdasági, kulturális vagy szociális azonosságára jellemző ismeret -, valamint az adatból levonható, az érintettre vonatkozó következtetés.</p>
<p>Hozzájárulás<br>a Felhasználó kívánságának önkéntes és határozott kinyilvánítása, amely megfelelő tájékoztatáson alapul, és amellyel félreérthetetlen beleegyezését adja a rá vonatkozó személyes adatok - teljes körű vagy egyes műveletekre kiterjedő – kezeléséhez.</p>
<p>Tiltakozás<br>a Felhasználó nyilatkozata, amellyel személyes adatainak kezelését kifogásolja, és az adatkezelés megszüntetését, illetve a kezelt adatok törlését kéri.</p>
<p>Adatkezelő<br>a Szolgáltató, aki az adatok kezelésének célját meghatározza, az adatkezelésre vonatkozó döntéseket meghozza és végrehajtja, vagy az általa megbízott adatfeldolgozóval végrehajtatja.</p>
<p>Adatkezelés<br>az alkalmazott eljárástól függetlenül az adatokon végzett bármely művelet vagy a műveletek összessége, így például gyűjtése, felvétele, rögzítése, rendszerezése, tárolása, megváltoztatása, felhasználása, továbbítása, nyilvánosságra hozatala, összehangolása vagy összekapcsolása, zárolása, törlése és megsemmisítése, valamint az adatok további felhasználásának megakadályozása. Adatkezelésnek számít a fénykép-, hang- vagy képfelvétel készítése, valamint a személy azonosítására alkalmas fizikai jellemzők (pl. ujj- vagy tenyérnyomat, DNS-minta, íriszkép) rögzítése is.</p>
<p>Adattovábbítás<br>ha az adatot meghatározott harmadik személy számára hozzáférhetővé teszik.</p>
<p>Nyilvánosságra hozatal<br>ha az adatot bárki számára hozzáférhetővé teszik.<br>Adattörlés<br>az adatok felismerhetetlenné tétele oly módon, hogy a helyreállításuk többé nem lehetséges.</p>
<p>Adatzárolás<br>az adat azonosító jelzéssel ellátása további kezelésének végleges vagy meghatározott időre történő korlátozása céljából.</p>
<p>Adatmegsemmisítés<br>az adatok vagy az azokat tartalmazó adathordozó teljes fizikai megsemmisítése.</p>
<p>Adatfeldolgozás<br>az adatkezelési műveletekhez kapcsolódó technikai feladatok elvégzése, függetlenül a műveletek végrehajtásához alkalmazott módszertől és eszköztől, valamint az alkalmazás helyétől, feltéve hogy a technikai feladatot az adatokon végzik.</p>
<p>Adatfeldolgozó<br>a Szolgáltató által a Honlap üzemeltetésével megbízott Üzemeltető, aki a személyes adatok feldolgozását végzi.</p>
<p>Harmadik személy<br>olyan természetes vagy jogi személy, illetve jogi személyiséggel nem rendelkező szervezet, amely vagy aki nem azonos a Felhasználóval, az Adatkezelővel (Szolgáltatóval) vagy az Adatfeldolgozóval (Üzemeltetővel).</p>
<p>Harmadik ország<br>minden olyan állam, amely nem EGT-állam.</p>
<p>Hatóság<br>a Nemzeti Adatvédelmi és Információszabadság Hatóság.</p>
<p>Különleges adat<br>a) a faji eredetre, a nemzeti és etnikai kisebbséghez tartozásra, a politikai véleményre vagy pártállásra, a vallásos vagy más világnézeti meggyőződésre, az érdek-képviseleti szervezeti tagságra, a szexuális életre vonatkozó személyes adat,</p>
<p>b) az egészségi állapotra, a kóros szenvedélyre vonatkozó személyes adat, valamint a bűnügyi személyes adat.</p>
<p>Üzemeltető<br>A Szolgáltató által a Honlap technikai üzemeltetésével megbízott jogi személy. <br></p>
<p>1.&nbsp;&nbsp;&nbsp; Az adatkezelés célja</p>
<p>a)&nbsp;&nbsp;&nbsp; a Honlap által nyújtott szolgáltatások igénybevételének, a Honlap használatának biztosítása;</p>
<p>b)&nbsp;&nbsp;&nbsp; &nbsp;a felhasználók külön hozzájárulása esetén, hogy a Szolgáltató közvetlen üzletszerzés vagy reklám céljából a későbbiekben a Felhasználók részére az általuk megadott elérhetőségeken kapcsolatfelvételt kezdeményezzen vagy reklámot küldjön;</p>
<p>c)&nbsp;&nbsp;&nbsp; Honlap statisztika gyűjtése a felhasználói szokások elemzése érdekében.</p>
<p>2.&nbsp;&nbsp;&nbsp; A Szolgáltató szolgáltatása nyújtása során Személyes adatot a Felhasználó önkéntes, előzetes Hozzájárulásával kezel. Cselekvőképtelen, korlátozottan cselekvőképes, illetve 16. éven aluli kiskorú személy hozzájáruló nyilatkozatához a törvényes képviselőjének hozzájárulását a Szolgáltató vélelmezi. Tájékoztatjuk Önt, hogy a Honlapon történő különböző versenyeken, játékokon, akciókon, szavazásokon, rejtvénypályázatokon, vagy regisztrációkon stb. részt vevő Felhasználók által személyesen, írásban, telefonon, SMS-ben, interneten, e-mailben való megadott személyes adatok nyilvántartásunkba kerülnek. Ön részvételével kifejezett hozzájárulását adja személyes adatainak a Szolgáltató általi nyilvántartásához és kezeléséhez.</p>
<p>3.&nbsp;&nbsp;&nbsp; A Szolgáltató Személyes adatot csak a jelen ÁSZF-ben meghatározott célból, jog gyakorlása és kötelezettség teljesítése érdekében kezel. A Szolgáltató kizárólag olyan Személyes adatot kezel, amely az adatkezelés céljának megvalósulásához elengedhetetlen, a cél elérésére alkalmas, csak a cél megvalósulásához szükséges mértékben és ideig.</p>
<p>4.&nbsp;&nbsp;&nbsp; A kezelt adatok köre:</p>
<p>a)&nbsp;&nbsp;&nbsp; a látogatás dátuma és időpontja, IP cím és domain név, az elért tartalom címe, név, felhasználói név, a-mail cím, jelszó; valamint</p>
<p>b)&nbsp;&nbsp;&nbsp; a Felhasználó választása szerint, születési hely és idő, nem, posta cím, saját blog/weboldal címe, kedvencek.</p>
<p>5.&nbsp;&nbsp;&nbsp; A Szolgáltató szolgáltatása nyújtása során Különleges adatot nem kezel.</p>
<p>6.&nbsp;&nbsp;&nbsp; Az adatkezelés időtartama az adatkezeléshez adott hozzájárulás visszavonásáig tart.</p>
<p>7.&nbsp;&nbsp;&nbsp; A Szolgáltató a Felhasználó Személyes adatait Harmadik személy részére (az Üzemeltetőt, mint Adatfeldolgozót kivéve) nem továbbítja. A Szolgáltató a személyes adatot harmadik országban adatkezelést folytató adatkezelő vagy adatfeldolgozást végző adatfeldolgozó részére nem továbbít. Tájékoztatjuk Önt, hogy a Honlapon megadott Személyes adatait a Szolgáltató magyarországi érdekeltségi körébe tartozó társaságok tárolják és kezelik és az Ön hozzájárulásával előfizetési akcióról, promóciókról tájékoztatót küldenek az ön részére. A személyes adatok nyilvántartásba vétele és kezelése az információs önrendelkezési jogról és az információszabadságról szóló 2011. évi CXII. törvény és a kutatás és a közvetlen üzletszerzés célját szolgáló név- és lakcímadatok kezeléséről szóló 1995.évi CXIX. törvény alapján történik. Ön adatainak kezeléséről bármikor ingyenesen tájékoztatást kérhet, kérheti adatai helyesbítését vagy indoklás nélkül, azonnali törlését az adatkezelőnél.</p>
<p>8.&nbsp;&nbsp;&nbsp; A Felhasználót az alábbi jogok illetik meg a Személyes adataira vonatkozón a Szolgáltatóval szemben:</p>
<p>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tájékoztatást kérhet személyes adatainak kezeléséről,</p>
<p>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tiltakozhat Személyes adatainak kezelése ellen,</p>
<p>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a Felhasználó személyes adatainak helyesbítését kérheti,</p>
<p>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; a Felhasználó személyes adatainak törlését vagy zárolását kérheti.</p>
<p>9.&nbsp;&nbsp;&nbsp; Szolgáltató a kérelem benyújtásától számított legrövidebb idő alatt, de legfeljebb 15 napon belül írásban, közérthetően formában megadni a tájékoztatást, illetve elvégezni a helyesbítést, törlést, zárolást. A kérelem teljesítése a Felhasználó számára ingyenes.</p>
<p>10. A Felhasználó Személyes adatait a Szolgáltató köteles törölni, ha</p>
<p>a)&nbsp;&nbsp;&nbsp; az adatkezelés jogellenes;</p>
<p>b)&nbsp;&nbsp;&nbsp; a Felhasználó a törlést kéri;</p>
<p>c)&nbsp;&nbsp;&nbsp; az hiányos vagy téves - és ez az állapot jogszerűen nem orvosolható -, feltéve, hogy a törlést törvény nem zárja ki;</p>
<p>d)&nbsp;&nbsp;&nbsp; az adatkezelés célja megszűnt, vagy az adatok tárolásának törvényben meghatározott határideje lejárt;</p>
<p>e)&nbsp;&nbsp;&nbsp; azt a Hatóság vagy a bíróság elrendelte.</p>
<p>11. Az adatkezelő Szolgáltató elérhetőségei:</p>
<p>Mediaworks Magazines Kiadó Kft.&nbsp;</p>
<p><br> Székhely: &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1082 Budapest, Futó u. 35-37.&nbsp;<br> Cégj.szám: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 01-09-185327&nbsp;<br> adószám: &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 24841973-2-43&nbsp;<br> E-mail: &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; adatkezeles@mediaworks.hu</p>
<p>12.&nbsp;&nbsp;&nbsp;&nbsp; Az adatkezeléssel kapcsolatos jogorvoslat érdekében, panasszal az alábbi Hatósághoz fordulhat:</p>
<p>Nemzeti Adatvédelmi és Információszabadság Hatóság</p>
<p>Székhely: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1125 Budapest, Szilágyi Erzsébet fasor 22/C.</p>
<p>Postacím: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1534 Bp. Pf.: 834</p>
<p>Telefon: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; +36-1-3911400</p>
<p>Telefax: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; +36-1-3911410</p>
<p>E-mail: ugyfelszolgalat@naih.hu</p>
<p>Web: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; http://www.naih.hu</p>
<p>V.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlapon alkalmazott Cookie-k</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Az Ön külön hozzájárulása esetén, a Honlap egyes részeinek letöltésekor automatikusan kisméretű, bizonyos esetben az Ön személyes adatait tartalmazó adatfile-okat helyezünk el az Ön számítógépén ("cookie"). A cookie célja az adott oldal minél magasabb színvonalú működésének biztosítása a felhasználó élmény növelése érdekében. Ennek megtörténtéről a Felhasználó a Szolgáltatótól nem kap további értesítést. A cookie-k a Honlap egyes funkcióinak működéséhez szükségesek, látogatásai alkalmával a korábbi cookie-k a Szolgáltatóhoz kerülnek.</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlapra való belépéssel számítógépének egyes paramétereiről, illetve annak IP címéről naplófile készül. Az adatok kizárólag statisztikai célokat szolgálnak, a Szolgáltató kizárólag a Weboldal fejlesztése érdekében használja fel őket - kivéve a jogszabályi kötelezés, illetve a hatósági eljárás eseteit. Az IP cím és a naplófile egyes esetekben személyes adatnak minősülhet.</p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A cookie-t a Felhasználó képes törölni saját számítógépéről, illetve beállíthatja böngészőjét, hogy a cookie-k alkalmazását tiltsa. A cookie-k alkalmazásának tiltásával a Felhasználó tudomásul veszi, hogy cookie nélkül az adott oldal működése nem teljes értékű.</p>
<p>VI.&nbsp;&nbsp;&nbsp; A Facebook és egyéb Külső szolgáltatók adatkezelése</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlapra történő belépés és regisztráció Facebook bejelentkezéssel is összekapcsolható, amely a Facebookos belépés és regisztráció a Facebook alkalmazáson keresztül történik meg.</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A kapcsolódást biztosító alkalmazás felvételével a Szolgáltató hozzáfér a Felhasználó Facebook alapadataihoz. A Facebook fiók és a Honlap összekötése eredményeként a Szolgáltató a Felhasználó következő adatait kezelheti: Facebook név, Facebook email cím, Facebook profil kép, Facebook nem, Facebook barátok listája.</p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Facebook és a Honlapra való belépés összekötését a Felhasználó bármikor megszüntetheti. Ebben az esetben a Facebookos alapadatait az Üzemeltető törli, de a Felhasználó a Honlapon létrejött aktivitásai nem kerülnek törlésre.</p>
<p>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Szolgáltató a Honlapra történő regisztrációt és belépést könnyítő a Facebookon túl, további Külső szolgáltatókkal is együttműködhet. A Külső szolgáltató rendszereiben az ott megadott adatok tekintetében a Külső szolgáltató saját adatvédelmi irányelvei az irányadók.</p>
<p>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Az egyes szolgáltatások keretében elérhetővé tett és a különböző közösségi oldalakon megosztott tartalmak vonatkozásában a tartalom megosztását lehetővé tevő Külső szolgáltató minősül a Személyes adatok kezelőjének, tevékenységére saját felhasználási feltételei és adatvédelmi szabályzata az irányadó. Ilyen külső közvetítő szolgáltatások például: Facebook, google, pinterest, tumblr, twitter, iwiw.</p>
<p><strong>VII. Moderálási alapelvek</strong></p>
<p>1.&nbsp;&nbsp;&nbsp; A Szolgáltató a Magyar Tartalomszolgáltatók Egyesülete (MTE) vonatkozó ajánlása alapján az interneten megjelenő felhasználói fórumokat az Alaptörvényben biztosított kommunikációs alapjogok kiteljesedése eszközeinek tekinti. Az Alkotmánybíróság több határozatában is hangsúlyozta, hogy a szabad véleménynyilvánításhoz való jog a véleményt annak érték- és igazságtartalmára való tekintet nélkül védi. A véleménynyilvánítási szabadság alapvető célja annak a lehetőségnek a biztosítása, hogy valaki mások véleményét formálja, másokat meggyőzzön saját álláspontjáról. A véleménynyilvánítás szabadsága általában mindenfajta közlés szabadságát magában foglalja, mégpedig függetlenül a közlés módjától és értékétől, erkölcsi minőségétől és többnyire valóságtartalmától is. A véleménynyilvánítás szabadságának kizárólag külső korlátai vannak; amíg egy ilyen alkotmányosan meghúzott külső korlátba nem ütközik, maga a véleménynyilvánítás lehetősége és ténye védett, ennek korlátozása alkotmányellenes. Tekintettel arra, hogy a fórumon szereplő közlések nem a tartalomszolgáltató információi, véleményei, azok ellenőrzésére csak utólag van mód. Az MTE véleménye szerint a tartalomszolgáltatóknak elsődlegesen arra kell törekedniük, hogy a kifogásolt felhasználói közlésekkel kapcsolatos ellentétes vélemények, információk azonos felületen való megjelenítése megtörténjen, biztosítva a véleménynyilvánítás szabadságát.</p>
<p>2.&nbsp;&nbsp;&nbsp; Ennek megfelelően a következő alapelvek szerint moderáljuk fórumainkat, illetve a cikkekhez és receptekhez tartozó hozzászólásokat:</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Korlátlan felelősséget csak az általunk szerkesztett tartalmakért vállalunk;</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ugyanakkor fenntartjuk a jogot a személyiségi és kisebbségi jogokat, az alkotmányos elveket sértő, illetve az öncélúan durva, trágár, ízléstelen, alpári hangnemben fogalmazott hozzászólások törlésére, amint azok tudomásunkra jutnak;</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fenntartjuk a jogot, hogy a Honlapon működő Gasztro-kvízben, vagy a szervezett nyereményjátékokkal kapcsolatban bármely módon jogsértő vagy durva, trágár, ízléstelen, alpári magatartást tanúsító Felhasználók fiókját előzetes értesítés, figyelmeztetés és indokolás nélkül töröljük, amint azok tudomásunkra jutnak;</p>
<p>-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A fórumokat, hozzászólásokat moderáljuk, ám elkerülheti figyelmünket egy-egy törvénysértés.</p>
<p>3.&nbsp;&nbsp;&nbsp; Amennyiben ilyen, vagy egyéb vitatható tartalmú hozzászólással találkozik, kérjük, jelezze ezt a mindmegette@mindmegette.hu e-mail címen.</p>
<p>4.&nbsp;&nbsp;&nbsp; A Szolgáltató, mint a Honlap tulajdonosa és szolgáltatója, nem vállal felelősséget a fórum- és egyéb szolgáltatásoldalain a látogatók által elhelyezett üzenetekért és csatolásokért (kép, hang, videó és bármilyen más média). A felelősség az üzenetet és a csatolást elhelyező személyt terheli.</p>
<p><strong>VIII.&nbsp;&nbsp; &nbsp;Szavatosság és felelősség</strong></p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Szolgáltató nem szavatolja, hogy a Honlapra történő belépés, a Honlap letöltése, vagy a Honlap használata mindenkor zavartalan, megszakításmentes és hibamentes lesz. Úgyszintén nem szavatolja, hogy bármely a honlapon megjelenő, vagy a honlapon keresztül elérhető anyag mindenkor hiba-, vírus-, illetve bármilyen egyéb káros tartalomtól mentes lesz.</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlap letöltéséből vagy elérhetetlenségéből eredő bármilyen kár megtérítését a Szolgáltató kizárja. A regisztráció során történő adatközlés hiányosságaiért, illetve a hibásan megadott adatokból adódó bármilyen következményért a Szolgáltató felelősséget nem vállal.</p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlapon található külső hivatkozások követésével letöltött tartalom nem áll a Szolgáltató befolyása alatt. Amennyiben azt az arra jogosult kéri, a linket a Szolgáltató törli vagy módosítja.</p>
<p>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Honlap hozzászólásaival kapcsolatban valamint a Honlapon megjelenő ajánlatok, hirdetések, tájékoztatók tartalma tekintetében a Szolgáltató minden felelősséget kizár. A Szolgáltató fenntartja a jogot a hozzászólások, illetve felhasználók által beküldött tartalom előzetes értesítés, figyelmeztetés és indokolás nélküli törlésére.</p>
<p>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ön beleegyezik abba, hogy a Szolgáltatóért teljes körűen helyt álljon minden harmadik személy részéről felmerülő igénnyel szemben, amely az Ön Honlap-használatával függ össze vagy abból ered, ideértve bármely természetű vagy fajtájú követelést, költséget, ami bármely igényből, hiányból, kárból (tényleges és következményes), perből, ítéletből, peres eljárás költségéből és ügyvédi költségből ered. Ezekben az esetekben az Üzemeltető írásban értesíti önt az igényről, perről vagy eljárásról.</p>
<p><strong>IX.&nbsp;&nbsp;&nbsp; &nbsp;A jelen ÁSZF hatálya</strong></p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Jelen ÁSZF 2015. október 27. napján lép hatályba és határozatlan időre szól.</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A Szolgáltató jogosult a jelen ÁSZF-et egyoldalúan módosítani. A Szolgáltató az új szabályzat hatálybalépésével és közzétételével egyidejűleg hirdetménnyel tájékoztatja a felhasználókat a Szabályzat módosításáról. A tájékoztatás tartalmazza a pontos utalást az ÁSZF módosított rendelkezéseire, a módosítás hatályba lépésének időpontját, a módosított ÁSZF elérhetőségét, a felhasználót megillető azonnali hatályú felmondás (leiratkozás) feltételeiről szóló tájékoztatást.</p>			